version: '3.8'
services:
  fetcher:
    build: .
    container_name:
      fetcher
    environment:
      RPC_ENDPOINT: ${RPC_ENDPOINT}
      N_TOP_WALLETS: ${N_TOP_WALLETS}
      N_BLOCKS: ${N_BLOCKS}
      LOG_LEVEL: ${LOG_LEVEL}
      SAVE_PATH: /data/${SAVE_PATH}
    volumes:
      - ./exported_data:/data
